In [12]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [13]:
df=pd.read_csv(r"D:\Data Analytics\DataSets\Influencer_ROI_Auditor_Messy_Dataset.csv")
df

,Influencer_ID,Influencer_Name,Platform,Influencer_Tier,Followers,Avg_Likes,Avg_Comments,Avg_Shares,Campaign_ID,Campaign_Cost,Revenue,ROI,Campaign_Type
0,INF0001,Influencer_1,YouTube,Macro,122958.0,10044.0,778.0,413,CAM00001,3142,10791,2.43,Giveaway
1,INF0001,Influencer_1,Instagram,Macro,522430.0,7955.0,1431.0,270,CAM00002,180,"$6,770",36.61,Promotion
2,INF0001,Influencer_1,YouTube,Macro,788201.0,59099.0,11275.0,592,CAM00003,1234,49952,39.48,Giveaway
3,INF0001,Influencer_1,YouTube,Mega,422909.0,4498.0,240.0,139,CAM00004,2608,5828,1.23,Product Launch
4,INF0001,Influencer_1,Facebook,Mega,655811.0,64032.0,5437.0,872,CAM00005,3055,46188,14.12,Promotion
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5045,INF0540,influencer_540,Instagram,Micro,463506.0,6324.0,897.0,267,CAM02696,385,5939,14.43,Product Launch
5046,INF0369,Influencer_369,YouTube,Macro,429082.0,34692.0,3861.0,1489,CAM01841,3696,29882,7.08,Giveaway
5047,INF0483,Influencer_483,Instagram,Micro,291318.0,10031.0,560.0,440,CAM02412,1706,12056,6.07,Product Launch
5048,INF0895,Influencer_895,YouTube,Micro,987944.0,59072.0,4967.0,2272,CAM04471,1470,42617,27.99,Promotion
5049,INF0001,Influencer_1,YouTube,Macro,788201.0,59099.0,11275.0,592,CAM00003,"$1,234",49952,39.48,Giveaway

In [3]:
df.shape

(5050, 13)

In [5]:
df.columns.tolist()

['Influencer_ID',
 'Influencer_Name',
 'Platform',
 'Influencer_Tier',
 'Followers',
 'Avg_Likes',
 'Avg_Comments',
 'Avg_Shares',
 'Campaign_ID',
 'Campaign_Cost',
 'Revenue',
 'ROI',
 'Campaign_Type']

In [6]:
df["Influencer_ID"].unique()

array(['INF0001', 'INF0002', 'INF0003', ..., ' INF0759 ', ' INF0083 ',
       ' INF0369 '], shape=(1229,), dtype=object)

In [7]:
df["Influencer_Name"].unique()

array(['Influencer_1', 'Influencer_2', 'Influencer_3', ...,
       'influencer_1000', 'influencer_781', 'influencer_741'],
      shape=(1231,), dtype=object)

In [8]:
df["Platform"].unique()

array(['YouTube', 'Instagram', 'Facebook'], dtype=object)

In [9]:
df["Influencer_Tier"].unique()

array(['Macro', 'Mega', 'Micro', 'Nano'], dtype=object)

In [34]:
df['Followers'].unique()

array([122958., 522430., 788201., ..., 680885., 979466., 718160.],
      shape=(4839,))

In [11]:
df["Avg_Likes"].unique()

array([10044.,  7955., 59099., ..., 71667., 49404.,  9146.], shape=(4668,))

In [14]:
df["Avg_Comments"].unique()

array([  778.,  1431., 11275., ...,  1219., 10389.,  3676.], shape=(3595,))

In [15]:
df["Avg_Shares"].unique()

array([ 413,  270,  592, ..., 3104, 2571, 2339], shape=(1997,))

In [16]:
df["Campaign_ID"].unique()

array(['CAM00001', 'CAM00002', 'CAM00003', ..., ' CAM03795 ',
       ' CAM00413 ', ' CAM01841 '], shape=(5004,), dtype=object)

In [17]:
df["Campaign_Cost"].unique()

array(['3142', '180', '1234', ..., '$145 ', '$581 ', '$1,234 '],
      shape=(3244,), dtype=object)

In [18]:
df["Revenue"].unique()

array(['10791', '$6,770 ', '49952', ..., '$10,402 ', '$17,787 ',
       '$28,750 '], shape=(4806,), dtype=object)

In [14]:
df=df.drop(columns=["ROI"])

In [15]:
df

,Influencer_ID,Influencer_Name,Platform,Influencer_Tier,Followers,Avg_Likes,Avg_Comments,Avg_Shares,Campaign_ID,Campaign_Cost,Revenue,Campaign_Type
0,INF0001,Influencer_1,YouTube,Macro,122958.0,10044.0,778.0,413,CAM00001,3142,10791,Giveaway
1,INF0001,Influencer_1,Instagram,Macro,522430.0,7955.0,1431.0,270,CAM00002,180,"$6,770",Promotion
2,INF0001,Influencer_1,YouTube,Macro,788201.0,59099.0,11275.0,592,CAM00003,1234,49952,Giveaway
3,INF0001,Influencer_1,YouTube,Mega,422909.0,4498.0,240.0,139,CAM00004,2608,5828,Product Launch
4,INF0001,Influencer_1,Facebook,Mega,655811.0,64032.0,5437.0,872,CAM00005,3055,46188,Promotion
...,...,...,...,...,...,...,...,...,...,...,...,...
5045,INF0540,influencer_540,Instagram,Micro,463506.0,6324.0,897.0,267,CAM02696,385,5939,Product Launch
5046,INF0369,Influencer_369,YouTube,Macro,429082.0,34692.0,3861.0,1489,CAM01841,3696,29882,Giveaway
5047,INF0483,Influencer_483,Instagram,Micro,291318.0,10031.0,560.0,440,CAM02412,1706,12056,Product Launch
5048,INF0895,Influencer_895,YouTube,Micro,987944.0,59072.0,4967.0,2272,CAM04471,1470,42617,Promotion
5049,INF0001,Influencer_1,YouTube,Macro,788201.0,59099.0,11275.0,592,CAM00003,"$1,234",49952,Giveaway

In [17]:
df=df.rename(columns={'Avg_Likes':'Likes','Avg_Comments':'Comments','Avg_Shares':'Shares'})

In [18]:
df

,Influencer_ID,Influencer_Name,Platform,Influencer_Tier,Followers,Likes,Comments,Shares,Campaign_ID,Campaign_Cost,Revenue,Campaign_Type
0,INF0001,Influencer_1,YouTube,Macro,122958.0,10044.0,778.0,413,CAM00001,3142,10791,Giveaway
1,INF0001,Influencer_1,Instagram,Macro,522430.0,7955.0,1431.0,270,CAM00002,180,"$6,770",Promotion
2,INF0001,Influencer_1,YouTube,Macro,788201.0,59099.0,11275.0,592,CAM00003,1234,49952,Giveaway
3,INF0001,Influencer_1,YouTube,Mega,422909.0,4498.0,240.0,139,CAM00004,2608,5828,Product Launch
4,INF0001,Influencer_1,Facebook,Mega,655811.0,64032.0,5437.0,872,CAM00005,3055,46188,Promotion
...,...,...,...,...,...,...,...,...,...,...,...,...
5045,INF0540,influencer_540,Instagram,Micro,463506.0,6324.0,897.0,267,CAM02696,385,5939,Product Launch
5046,INF0369,Influencer_369,YouTube,Macro,429082.0,34692.0,3861.0,1489,CAM01841,3696,29882,Giveaway
5047,INF0483,Influencer_483,Instagram,Micro,291318.0,10031.0,560.0,440,CAM02412,1706,12056,Product Launch
5048,INF0895,Influencer_895,YouTube,Micro,987944.0,59072.0,4967.0,2272,CAM04471,1470,42617,Promotion
5049,INF0001,Influencer_1,YouTube,Macro,788201.0,59099.0,11275.0,592,CAM00003,"$1,234",49952,Giveaway

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5050 entries, 0 to 5049
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Influencer_ID    5050 non-null   object
 1   Influencer_Name  5050 non-null   object
 2   Platform         5050 non-null   object
 3   Influencer_Tier  5050 non-null   object
 4   Followers        4899 non-null   float64
 5   Likes            4901 non-null   float64
 6   Comments         4898 non-null   float64
 7   Shares           5050 non-null   int64
 8   Campaign_ID      5050 non-null   object
 9   Campaign_Cost    4896 non-null   float64
 10  Revenue          5050 non-null   object
 11  ROI              5050 non-null   float64
 12  Campaign_Type    5050 non-null   object
dtypes: float64(5), int64(1), object(7)
memory usage: 513.0+ KB

In [10]:
df.isnull().sum()

Influencer_ID        0
Influencer_Name      0
Platform             0
Influencer_Tier      0
Followers          151
Likes              149
Comments           152
Shares               0
Campaign_ID          0
Campaign_Cost      154
Revenue              0
ROI                  0
Campaign_Type        0
dtype: int64

In [6]:
print((df.isnull().sum() / len(df)) * 100)

Influencer_ID      0.000000
Influencer_Name    0.000000
Platform           0.000000
Influencer_Tier    0.000000
Followers          2.990099
Avg_Likes          2.950495
Avg_Comments       3.009901
Avg_Shares         0.000000
Campaign_ID        0.000000
Campaign_Cost      3.049505
Revenue            0.000000
ROI                0.000000
Campaign_Type      0.000000
dtype: float64

In [20]:
df['Campaign_Cost']=df['Campaign_Cost'].astype(str).str.replace('$', '', regex=False).str.replace(',', '', regex=False).str.strip()
df['Revenue']=df['Revenue'].astype(str).str.replace('$', '', regex=False).str.replace(',', '', regex=False).str.strip()

In [21]:
df['Campaign_Cost'] = pd.to_numeric(df['Campaign_Cost'], errors='coerce')
df['Revenue'] = pd.to_numeric(df['Revenue'], errors='coerce')

In [22]:
df

,Influencer_ID,Influencer_Name,Platform,Influencer_Tier,Followers,Likes,Comments,Shares,Campaign_ID,Campaign_Cost,Revenue,Campaign_Type
0,INF0001,Influencer_1,YouTube,Macro,122958.0,10044.0,778.0,413,CAM00001,3142.0,10791,Giveaway
1,INF0001,Influencer_1,Instagram,Macro,522430.0,7955.0,1431.0,270,CAM00002,180.0,6770,Promotion
2,INF0001,Influencer_1,YouTube,Macro,788201.0,59099.0,11275.0,592,CAM00003,1234.0,49952,Giveaway
3,INF0001,Influencer_1,YouTube,Mega,422909.0,4498.0,240.0,139,CAM00004,2608.0,5828,Product Launch
4,INF0001,Influencer_1,Facebook,Mega,655811.0,64032.0,5437.0,872,CAM00005,3055.0,46188,Promotion
...,...,...,...,...,...,...,...,...,...,...,...,...
5045,INF0540,influencer_540,Instagram,Micro,463506.0,6324.0,897.0,267,CAM02696,385.0,5939,Product Launch
5046,INF0369,Influencer_369,YouTube,Macro,429082.0,34692.0,3861.0,1489,CAM01841,3696.0,29882,Giveaway
5047,INF0483,Influencer_483,Instagram,Micro,291318.0,10031.0,560.0,440,CAM02412,1706.0,12056,Product Launch
5048,INF0895,Influencer_895,YouTube,Micro,987944.0,59072.0,4967.0,2272,CAM04471,1470.0,42617,Promotion
5049,INF0001,Influencer_1,YouTube,Macro,788201.0,59099.0,11275.0,592,CAM00003,1234.0,49952,Giveaway

In [23]:
# Replace all NaNs in a Likes and Comments Columns with 0
df['Likes'] = df['Likes'].fillna(0)

In [24]:
df['Comments'] = df['Comments'].fillna(0)

In [25]:
# Filling missing values in Followers column with Median of their specific Influencer_Tier
df['Followers'] = df.groupby('Influencer_Tier')['Followers'].transform(lambda x: x.fillna(x.median()))

In [26]:
# Filling missing values in Campaign_Cost column with Median of their specific Influencer_Tier
df['Campaign_Cost'] = df.groupby('Influencer_Tier')['Campaign_Cost'].transform(lambda x: x.fillna(x.median()))

In [27]:
df.isnull().sum()

Influencer_ID      0
Influencer_Name    0
Platform           0
Influencer_Tier    0
Followers          0
Likes              0
Comments           0
Shares             0
Campaign_ID        0
Campaign_Cost      0
Revenue            0
Campaign_Type      0
dtype: int64

In [28]:
print((df.isnull().sum() / len(df)) * 100)

Influencer_ID      0.0
Influencer_Name    0.0
Platform           0.0
Influencer_Tier    0.0
Followers          0.0
Likes              0.0
Comments           0.0
Shares             0.0
Campaign_ID        0.0
Campaign_Cost      0.0
Revenue            0.0
Campaign_Type      0.0
dtype: float64

In [29]:
# Strip hidden spaces from ID columns
df['Campaign_ID'] = df['Campaign_ID'].str.strip()
df['Influencer_ID'] = df['Influencer_ID'].str.strip()

In [30]:
#Check and remove duplicate rows
print(f"Duplicates before: {df.duplicated().sum()}")

Duplicates before: 43

In [31]:
df = df.drop_duplicates().reset_index(drop=True)
print(f"Duplicates after: {df.duplicated().sum()}")

Duplicates after: 0

In [32]:
df

,Influencer_ID,Influencer_Name,Platform,Influencer_Tier,Followers,Likes,Comments,Shares,Campaign_ID,Campaign_Cost,Revenue,Campaign_Type
0,INF0001,Influencer_1,YouTube,Macro,122958.0,10044.0,778.0,413,CAM00001,3142.0,10791,Giveaway
1,INF0001,Influencer_1,Instagram,Macro,522430.0,7955.0,1431.0,270,CAM00002,180.0,6770,Promotion
2,INF0001,Influencer_1,YouTube,Macro,788201.0,59099.0,11275.0,592,CAM00003,1234.0,49952,Giveaway
3,INF0001,Influencer_1,YouTube,Mega,422909.0,4498.0,240.0,139,CAM00004,2608.0,5828,Product Launch
4,INF0001,Influencer_1,Facebook,Mega,655811.0,64032.0,5437.0,872,CAM00005,3055.0,46188,Promotion
...,...,...,...,...,...,...,...,...,...,...,...,...
5002,INF0413,Influencer_413,YouTube,Nano,628761.0,9146.0,1370.0,117,CAM02061,3957.0,11500,Product Launch
5003,INF0354,Influencer_354,YouTube,Micro,448166.0,14061.0,1504.0,408,CAM01766,4448.0,24362,Product Launch
5004,INF0156,Influencer_156,Facebook,Micro,15389.0,1363.0,0.0,45,CAM00779,2492.0,5620,Promotion
5005,INF0965,Influencer_965,Facebook,Micro,629322.0,56187.0,5643.0,1173,CAM04822,4478.0,61037,Giveaway
5006,INF0741,influencer_741,Facebook,Mega,997378.0,26861.0,2225.0,340,CAM03701,3666.0,27301,Promotion

In [33]:
# Convert count-based columns to Integers
# (Since you've handled NaNs, we can use int64)
int_cols = ['Followers', 'Likes', 'Comments', 'Shares', 'Revenue']
for col in int_cols:
    df[col] = df[col].astype('int64')

In [34]:
# Convert repeating text labels to Categories
# This is a best practice for columns like Platform and Tier
cat_cols = ['Platform', 'Influencer_Tier', 'Campaign_Type']
for col in cat_cols:
    df[col] = df[col].astype('category')

In [35]:
# Convert IDs to explicit Strings
df['Campaign_ID'] = df['Campaign_ID'].astype('string')
df['Influencer_ID'] = df['Influencer_ID'].astype('string')

In [37]:
# Final verification
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5007 entries, 0 to 5006
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Influencer_ID    5007 non-null   string
 1   Influencer_Name  5007 non-null   object
 2   Platform         5007 non-null   category
 3   Influencer_Tier  5007 non-null   category
 4   Followers        5007 non-null   int64
 5   Likes            5007 non-null   int64
 6   Comments         5007 non-null   int64
 7   Shares           5007 non-null   int64
 8   Campaign_ID      5007 non-null   string
 9   Campaign_Cost    5007 non-null   float64
 10  Revenue          5007 non-null   int64
 11  Campaign_Type    5007 non-null   category
dtypes: category(3), float64(1), int64(5), object(1), string(2)
memory usage: 367.3+ KB
None

In [64]:
# Strip whitespace from all string columns
df = df.apply(lambda x: x.str.strip() if x.dtype == "object" else x)

# Standardize Influencer_Name to Title Case
df['Influencer_Name'] = df['Influencer_Name'].str.title()

In [66]:
# Check null counts
print(df.isnull().sum())

Influencer_ID      0
Influencer_Name    0
Platform           0
Influencer_Tier    0
Followers          0
Likes              0
Comments           0
Shares             0
Campaign_ID        0
Campaign_Cost      0
Revenue            0
ROI                0
Campaign_Type      0
dtype: int64

In [38]:
df = df.drop_duplicates()

In [39]:
df.duplicated().sum()

np.int64(0)

In [40]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5007 entries, 0 to 5006
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Influencer_ID    5007 non-null   string
 1   Influencer_Name  5007 non-null   object
 2   Platform         5007 non-null   category
 3   Influencer_Tier  5007 non-null   category
 4   Followers        5007 non-null   int64
 5   Likes            5007 non-null   int64
 6   Comments         5007 non-null   int64
 7   Shares           5007 non-null   int64
 8   Campaign_ID      5007 non-null   string
 9   Campaign_Cost    5007 non-null   float64
 10  Revenue          5007 non-null   int64
 11  Campaign_Type    5007 non-null   category
dtypes: category(3), float64(1), int64(5), object(1), string(2)
memory usage: 367.3+ KB

In [41]:
# Converting Influencer_Name object to string
df['Influencer_Name'] = df['Influencer_Name'].astype('string')

In [42]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5007 entries, 0 to 5006
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Influencer_ID    5007 non-null   string
 1   Influencer_Name  5007 non-null   string
 2   Platform         5007 non-null   category
 3   Influencer_Tier  5007 non-null   category
 4   Followers        5007 non-null   int64
 5   Likes            5007 non-null   int64
 6   Comments         5007 non-null   int64
 7   Shares           5007 non-null   int64
 8   Campaign_ID      5007 non-null   string
 9   Campaign_Cost    5007 non-null   float64
 10  Revenue          5007 non-null   int64
 11  Campaign_Type    5007 non-null   category
dtypes: category(3), float64(1), int64(5), string(3)
memory usage: 367.3 KB

In [ ]:
df

,Influencer_ID,Influencer_Name,Platform,Influencer_Tier,Followers,Likes,Comments,Shares,Campaign_ID,Campaign_Cost,Revenue,Campaign_Type
0,INF0001,Influencer_1,YouTube,Macro,122958,10044,778,413,CAM00001,3142.0,10791,Giveaway
1,INF0001,Influencer_1,Instagram,Macro,522430,7955,1431,270,CAM00002,180.0,6770,Promotion
2,INF0001,Influencer_1,YouTube,Macro,788201,59099,11275,592,CAM00003,1234.0,49952,Giveaway
3,INF0001,Influencer_1,YouTube,Mega,422909,4498,240,139,CAM00004,2608.0,5828,Product Launch
4,INF0001,Influencer_1,Facebook,Mega,655811,64032,5437,872,CAM00005,3055.0,46188,Promotion
...,...,...,...,...,...,...,...,...,...,...,...,...
5002,INF0413,Influencer_413,YouTube,Nano,628761,9146,1370,117,CAM02061,3957.0,11500,Product Launch
5003,INF0354,Influencer_354,YouTube,Micro,448166,14061,1504,408,CAM01766,4448.0,24362,Product Launch
5004,INF0156,Influencer_156,Facebook,Micro,15389,1363,0,45,CAM00779,2492.0,5620,Promotion
5005,INF0965,Influencer_965,Facebook,Micro,629322,56187,5643,1173,CAM04822,4478.0,61037,Giveaway
5006,INF0741,influencer_741,Facebook,Mega,997378,26861,2225,340,CAM03701,3666.0,27301,Promotion

In [ ]:
df.to_csv("output.csv",index=False)